# Generated by Django 4.1.1 on 2022-10-31 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('English_App', '0005_contactinfo_contactpost_rename_user_profile_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='contactposts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email_address', models.EmailField(max_length=150)),
                ('phone_number', models.IntegerField(max_length=30)),
                ('body', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='contactpost',
        ),
    ]
