# Generated by Django 4.1.1 on 2022-10-31 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('English_App', '0006_contactposts_delete_contactpost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactposts',
            name='phone_number',
            field=models.IntegerField(blank=True),
        ),
    ]
