# Generated by Django 4.1.1 on 2022-10-31 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('English_App', '0008_usersposts'),
    ]

    operations = [
        migrations.DeleteModel(
            name='usersPosts',
        ),
    ]
