# Generated by Django 4.1.1 on 2022-11-12 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('English_App', '0010_usersposts'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactposts',
            options={'permissions': (('Can_Add_Contact', 'Can add contactpost'),)},
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
