# Generated by Django 4.1.1 on 2022-11-17 02:07

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('English_App', '0013_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addcoursemodel',
            name='courseBody',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
