# Generated by Django 4.1.1 on 2022-11-17 05:33

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('English_App', '0014_alter_addcoursemodel_coursebody'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersposts',
            name='body',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
