# Generated by Django 4.1.1 on 2022-11-17 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('English_App', '0015_alter_usersposts_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.CharField(max_length=50),
        ),
    ]
