# Generated by Django 4.1.1 on 2022-11-18 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('English_App', '0017_addcomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addcomment',
            name='post',
            field=models.CharField(max_length=80),
        ),
    ]
