# Generated by Django 4.1.1 on 2022-11-19 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('English_App', '0018_alter_addcomment_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.CharField(max_length=80),
        ),
    ]
