# Generated by Django 4.1.1 on 2022-11-19 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('English_App', '0020_createcomment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='addcomment',
            options={},
        ),
    ]
