# Generated by Django 4.1.1 on 2022-11-19 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('English_App', '0021_alter_addcomment_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addcomment',
            old_name='post',
            new_name='posts',
        ),
    ]
