# Generated by Django 4.1.1 on 2022-11-19 05:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('English_App', '0024_delete_createcomment'),
    ]

    operations = [
        migrations.CreateModel(
            name='createComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('body', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('articles', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ourcomments', to='English_App.usersposts')),
            ],
        ),
    ]
