# Generated by Django 4.1.1 on 2022-11-30 01:43

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('English_App', '0025_createcomment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactposts',
            options={},
        ),
        migrations.AlterField(
            model_name='contactposts',
            name='body',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contactposts',
            name='email_address',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='contactposts',
            name='phone_number',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='createcomment',
            name='articles',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='English_App.usersposts'),
        ),
    ]
