# Generated by Django 4.1.1 on 2022-11-30 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('English_App', '0026_alter_contactposts_options_alter_contactposts_body_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='createcomment',
            old_name='body',
            new_name='Comment',
        ),
    ]
