# Generated by Django 4.1.1 on 2022-11-30 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('English_App', '0027_rename_body_createcomment_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='createcomment',
            old_name='Comment',
            new_name='comment',
        ),
    ]
