# Generated by Django 4.1.1 on 2022-12-01 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('English_App', '0029_alter_createcomment_articles'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddHomework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('homeworkname', models.CharField(max_length=80)),
                ('topic', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
