# Generated by Django 4.1.1 on 2023-02-19 17:59

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('English_App', '0030_addhomework'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addhomework',
            name='topic',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
